import type { IBaseCommand, CommandType } from "@tryforge/forgescript";
export default {
    type: "interactionCreate",
    allowedInteractionTypes: ["button", "selectMenu"],
    code: `
    $onlyIf[$advancedTextSplit[$customID;_;0]==musicplayer;]
    $let[cid;$getCache[initclientmusic;musicplayer_message_$guildID_channelid]]
    $let[mid;$getCache[initclientmusic;musicplayer_message_$guildID_messageid]]
    $onlyIf[$get[mid]==$messageID;
    $interactionUpdate[
    $fetchResponse
    $disableComponents
    ]]
    $let[crdjcs_0f;$callFunction[checkDJRoleUser]]
    $if[$get[crdjcs_0f]==false;
    $onlyIf[$and[$voiceID[$guildID;$clientID]!=;$voiceID[$guildID;$authorID]!=$voiceID[$guildID;$clientID]]!=true;]
    ;
    $let[crdjcr_0f;$advancedTextSplit[$get[crdjcs_0f];|;1]]
    $onlyIf[$hasRoles[$guildID;$authorID;$get[crdjcr_0f]];$ephemeral $replace[$callFunction[useCustomMusicMessage;config_errorIsSameDJVC];{role};<@&$get[crdjcr_0f]>]]
    ]
    $if[$advancedTextSplit[$customID;_;1]==247musicidle;
    $if[$getCache[initclientmusic;musicplayer_message_$guildID_is247music]==true;
    $callFunction[bulkMusicPlayer;false]
    $let[jjck;$callFunction[destroyPlayer]]
    $interactionUpdate[
    $callFunction[idlePlayerMessage]
    $disableComponents
    ]]
    $stop
    ]
    $onlyIf[$try[$isPlaying;false]]
    $if[$advancedTextSplit[$customID;_;1]==nodequeue;
    $!clearInterval[intervalmusicmessage_$guildID_$get[cid]]
    $if[$selectMenuValues[0]==0;
    $!skipTrack
    ;
    $!skipTo[$selectMenuValues[0]]
    ]
    $!deferUpdate
    ]
    $if[$advancedTextSplit[$customID;_;1]==loop;
    $if[$getLoopMode==OFF;$setLoopMode[TRACK];
    $if[$getLoopMode==TRACK;$setLoopMode[QUEUE];$setLoopMode[OFF]
    ]]]
    $if[$advancedTextSplit[$customID;_;1]==shuffle;
    $let[statusshuffle;$getCache[initclientmusic;musicplayer_message_$guildID_isshuffle]]
    $if[$get[statusshuffle];
    $!unShuffleQueue
    $setCache[initclientmusic;musicplayer_message_$guildID_isshuffle;false]
    ;
    $!shuffleQueue
    $setCache[initclientmusic;musicplayer_message_$guildID_isshuffle;true]
    ]]
    $if[$advancedTextSplit[$customID;_;1]==lyrics;
    $ephemeral
    $let[f-fetch;false]
    $let[md5urltk;$md5[$trackInfo[url]]]
    
    $if[$callFunction[configMusic;preloadLyricsPlayer]==false;
    $let[lrkggno;$getCache[initclientmusic;musicplayer_cache-lyrics-$get[md5urltk]]]
    $if[$get[lrkggno]==null;
    $interactionReply[$callFunction[useCustomMusicMessage;config_errorNoResultLyrics]]
    $stop
    ]
    $async[
    $if[$or[$get[lrkggno]==;$get[lrkggno]==undefined];
    $jsonLoad[result;$callFunction[getLyricsTrack;$if[$checkContains[$toLowercase[$toCamelCase[$trackInfo[title]]];$toLowercase[$toCamelCase[$trim[$advancedTextSplit[$trackInfo[author];-;0]]]]]==false;$trim[$advancedTextSplit[$trackInfo[author];-;0]] - $advancedTextSplit[$trackInfo[title];(;0];$advancedTextSplit[$trackInfo[title];(;0]];;false;false]]
    ;
    $jsonLoad[result;$get[lrkggno]]
    ]
    $if[$env[result;results]==;$let[f-fetch;null];$let[f-fetch;true]]
    ]
    ;
    $let[kkvnm;$if[$checkContains[$toLowercase[$toCamelCase[$trackInfo[title]]];$toLowercase[$toCamelCase[$trim[$advancedTextSplit[$trackInfo[author];-;0]]]]]==false;$trim[$advancedTextSplit[$trackInfo[author];-;0]] - $advancedTextSplit[$trackInfo[title];(;0];$advancedTextSplit[$trackInfo[title];(;0]]]
    ]
    $defer
    $loop[-1;
    $if[$callFunction[configMusic;preloadLyricsPlayer]==true;

    $let[lrkggn;$getCache[initclientmusic;musicplayer_cache-lyrics-$get[md5urltk]]]
    $if[$get[lrkggn]!=undefined;
    $if[$get[lrkggn]!=null;
    $jsonLoad[result;$get[lrkggn]]
    ;
    $let[f-fetch;null]
    ]
    $break
    ]]
    $if[$get[f-fetch]!=false;$break]
    $wait[5]
    ]
    $if[$get[f-fetch]==null;
    $setCache[initclientmusic;musicplayer_cache-lyrics-$get[md5urltk];"null"]
    $interactionReply[$callFunction[useCustomMusicMessage;config_errorNoResultLyrics]]
    $stop
    ]
    $let[loadlyrics;$env[result;results;lyric]]
    $interactionReply[
    $if[$charCount[$get[loadlyrics]]>3000;$attachment[$get[loadlyrics];lyrics-$getTimestamp.txt;true]]
    $title[$decodeURI[$env[result;results;autocomplete]];$env[result;results;url]]
    $description[$codeBlock[$cropText[$get[loadlyrics];0;3000;\n\n($callFunction[useCustomMusicMessage;config_errorOverResultLyrics])]]]
    $footer[$toTitleCase[$env[result;results;provider]];$callFunction[useIcon;$env[result;results;provider]]]
    $thumbnail[$env[result;results;thumbnail]]
    $color[$callFunction[useIcon;color_embed]]
    $timestamp
    ]
    $setCache[initclientmusic;musicplayer_cache-lyrics-$get[md5urltk];$jsonStringify[result]]
    ]
    $if[$advancedTextSplit[$customID;_;1]==lastfm;
    $ephemeral
    $interactionReply[
    $footer[Fetching;$callFunction[useIcon;loading];0]
    $color[$callFunction[useIcon;color_embed];0]
    $footer[Fetching;$callFunction[useIcon;loading];1]
    $color[$callFunction[useIcon;color_embed];1]
    ]
    $let[trackTitle;$trim[$advancedTextSplit[$trackInfo[author];- Topic;0]]]
    $let[a;$callFunction[lastFmArtist;$get[trackTitle];false]]
    $if[$get[a]==null;
    $let[ak;$callFunction[lastFmArtistAPI;$get[trackTitle];false]]
    $onlyIf[$get[ak]!=null;$callFunction[useCustomMusicMessage;config_errorNoResultSearch]]
    $interactionReply[$callFunction[lastFmArtistAPI;$get[trackTitle]]]
    ;
    $interactionReply[$callFunction[lastFmArtist;$get[trackTitle]]]
    ]]
    $if[$advancedTextSplit[$customID;_;1]==volumedown;
    $!setVolume[$if[$sub[$getVolume;10]>=0;$sub[$getVolume;10];0]]
    ]
    $if[$advancedTextSplit[$customID;_;1]==volumeup;
    $!setVolume[$if[$sum[$getVolume;10]<=150;$sum[$getVolume;10];150]]
    ]
    $if[$advancedTextSplit[$customID;_;1]==volumemute;
    $!setVolume[$if[$getVolume==0;50;0]]
    ]
    $if[$advancedTextSplit[$customID;_;1]==stopplayer;
    $!clearInterval[intervalmusicmessage_$guildID_$get[cid]]
    $deleteCache[initclientmusic;cachesearchistory_user_autocomplete_$authorID]
    $deleteCache[initclientmusic;musicplayer_message_$guildID_isdynamicmusic]
    $if[$getCache[initclientmusic;musicplayer_message_$guildID_is247music]!=true;
    $async[$leaveVoiceChannel]
    ;
    $async[
    $if[$or[$getCache[initclientmusic;musicplayer_message_$guildID_ongoingplaylistmusic]==true;$getCache[initclientmusic;musicplayer_message_$guildID_ongoingdynamicmusic]==true];
    $if[$getCache[initclientmusic;musicplayer_message_$guildID_ongoingdynamicmusic]==true;
    $setCache[initclientmusic;musicplayer_message_$guildID_ongoingdynamicmusic;false]
    ]
    $if[$getCache[initclientmusic;musicplayer_message_$guildID_ongoingplaylistmusic]==true;
    $setCache[initclientmusic;musicplayer_message_$guildID_ongoingplaylistmusic;false]
    ]
    $loop[-1;
    $let[cf-fetch;$default[$getCache[initclientmusic;musicplayer_message_$guildID_ongoingplaylistmusic];$getCache[initclientmusic;musicplayer_message_$guildID_ongoingdynamicmusic]]]
    $if[$or[$get[cf-fetch]==false;$get[cf-fetch]==true]==false;$break]
    $wait[10]
    ]]
    $!stopTrack
    ]]
    $!deferUpdate
    ]
    $if[$advancedTextSplit[$customID;_;1]==actionplayer;
    $async[$if[$isPaused;$!resumeTrack;$!pauseTrack]]
    $!deferUpdate
    ]
    $if[$advancedTextSplit[$customID;_;1]==seekdown;
    $if[$getCache[initclientmusic;musicplayer_message_$guildID_attemptseek]==true;$ephemeral $interactionReply[$callFunction[useCustomMusicMessage;config_errorProcessSeek]] $stop]
    $ephemeral
    $defer
    $if[$callFunction[configMusic;interval_message]==true;
    $!clearInterval[intervalmusicmessage_$guildID_$get[cid]]
    $setCache[initclientmusic;musicplayer_message_$guildID_attemptseek;true]
    ]
    $async[
    $let[curduration;$if[$callFunction[configMusic;interval_message];$callFunction[musicVirtualDuration;$guildID;$get[cid]];$playerElapsedTime]]
    $let[seeks;10000]
    $let[tests;$callFunction[musicVirtualDuration;$guildID;$get[cid];$sub[$get[curduration];$get[seeks]]]]
    $setCache[initclientmusic;musicplayer_message_$guildID_attemptseek;true]
    $let[resseek;$if[$sub[$get[curduration];$get[seeks]]<0;0;$sub[$get[curduration];$get[seeks]]]]
    $!seekTrack[$get[resseek]]
    ]
    $!interactionDelete
    ]
    $if[$advancedTextSplit[$customID;_;1]==seekup;
    $if[$getCache[initclientmusic;musicplayer_message_$guildID_attemptseek]==true;$ephemeral $interactionReply[$callFunction[useCustomMusicMessage;config_errorProcessSeek]] $stop]
    $ephemeral
    $defer
    $if[$callFunction[configMusic;interval_message]==true;
    $!clearInterval[intervalmusicmessage_$guildID_$get[cid]]
    $setCache[initclientmusic;musicplayer_message_$guildID_attemptseek;true]
    ]
    $async[
    $let[curduration;$if[$callFunction[configMusic;interval_message];$callFunction[musicVirtualDuration;$guildID;$get[cid]];$playerElapsedTime]]
    $let[seeks;10000]
    $let[tests;$callFunction[musicVirtualDuration;$guildID;$get[cid];$sum[$get[curduration];$get[seeks]]]]
    $setCache[initclientmusic;musicplayer_message_$guildID_attemptseek;true]
    $let[resseek;$if[$sum[$get[curduration];$get[seeks]]<0;0;$sum[$get[curduration];$get[seeks]]]]
    $!seekTrack[$get[resseek]]
    ]
    $!interactionDelete
    ]
    $if[$advancedTextSplit[$customID;_;1]==dynamic;
    $callFunction[setAutoplay]
    ]
    $if[$advancedTextSplit[$customID;_;1]==247music;
    $setCache[initclientmusic;musicplayer_message_$guildID_is247music;$checkCondition[$getCache[initclientmusic;musicplayer_message_$guildID_is247music]!=true]]
    ]
    $onlyIf[$checkContains[$advancedTextSplit[$customID;_;1];stopplayer;lyrics;nodequeue;seekup;seekdown;lastfm;actionplayer]!=true;]
    $callFunction[updateCurrentMusicPlayer;true]
    `
} satisfies IBaseCommand<CommandType>;
