import type { IForgeFunction } from "@tryforge/forgescript";
export default {
    name: "extractTrack",
    params: [{
        name: "url", // string
        description: "To provide a information",
        required: true
    },
    {
        name: "userAgent", // string
        description: "Spoof Client",
        required: false
    },
    {
        name: "limitChar", // int
        description: "Limit Character to 2000",
        required: false
    }],
    code: `
    $let[url;$env[url]]
    $let[spliturl;$advancedTextSplit[$get[url];://;1]]
    $let[agent;$if[$or[$env[userAgent]==;$env[userAgent]==null];$callFunction[configMusic;default_userAgent_desktop];$env[userAgent]]]
    $jsonLoad[filterid;$callFunction[filterMediaID;https://$get[spliturl]]]
    $onlyIf[$or[$env[filterid;id]==null;$env[filterid;type]==null]!=true;$return]
    $arrayLoad[results]
    
    $if[$env[filterid;type]==youtube;
    $let[tryattempt;0]
    $localFunction[refreshyt;
    $if[$env[retry]==true;
    $if[$get[tryattempt]>=3;$return]
    $letSum[tryattempt;1]
    ]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpSetBody[{"videoId":"$env[filterid;id]","context":{"client":{"clientName":2,"clientVersion":"2.20261231","visitorData":"$getCache[initclientmusic;authmusic_youtube_visitor]"}}}]
    $httpAddHeader[Accept-Encoding;gzip, br]
    $httpAddHeader[Cookie;$getCache[initclientmusic;authmusic_youtube_tempcookies]]
    $httpSetContentType[Text]
    $let[http;$httpRequest[https://m.youtube.com/youtubei/v1/player?prettyPrint=false&fields=responseContext(visitorData),playabilityStatus,videoDetails(videoId,title,lengthSeconds,channelId,isCrawlable,viewCount,author,isPrivate,isLiveContent);POST;reshttp]]
    $jsonLoad[reshttp;$env[reshttp]]
    $c[Fallback]
    $if[$and[$env[reshttp;playabilityStatus;status]!=OK;$env[reshttp;videoDetails;videoId]==];
    $httpAddHeader[User-Agent;$get[agent]]
    $httpAddHeader[Accept-Encoding;gzip, br]
    $httpAddHeader[Cookie;$getCache[initclientmusic;authmusic_youtube_tempcookies]]
    $httpSetContentType[Text]
    $let[http2;$httpRequest[https://www.youtube.com/watch?v=$env[filterid;id];GET]]
    $let[outputhtyt;$advancedTextSplit[$httpResult;var ytInitialData =;1;\\;;0]]
    $onlyIf[$isJSON[$get[outputhtyt]];$callLocalFunction[refreshyt;true] $return]
    $jsonLoad[reshttptest;{}]
    $jsonLoad[reshttp2;$get[outputhtyt]]
    $jsonLoad[resfindindex;$env[reshttp2;contents;twoColumnWatchNextResults;results;results;contents]]
    $!jsonSet[reshttptest;videoId;$env[reshttp2;currentVideoEndpoint;watchEndpoint;videoId]]
    $!jsonSet[reshttptest;title;$env[reshttp2;contents;twoColumnWatchNextResults;results;results;contents;$arrayFindIndex[resfindindex;g;$checkCondition[$env[g;videoPrimaryInfoRenderer]!=]];videoPrimaryInfoRenderer;title;runs;0;text]]
    $!jsonSet[reshttptest;lengthSeconds;0] $c[i couldn't find which data return that]
    $!jsonSet[reshttptest;channelId;$env[reshttp2;contents;twoColumnWatchNextResults;results;results;contents;$arrayFindIndex[resfindindex;g;$checkCondition[$env[g;videoSecondaryInfoRenderer]!=]];videoSecondaryInfoRenderer;owner;videoOwnerRenderer;navigationEndpoint;browseEndpoint;browseId]]
    $!jsonSet[reshttptest;isCrawlable;true] $c[i couldn't find which data return that]
    $!jsonSet[reshttptest;viewCount;"$advancedReplace[$advancedTextSplit[$env[reshttp2;contents;twoColumnWatchNextResults;results;results;contents;$arrayFindIndex[resfindindex;g;$checkCondition[$env[g;videoPrimaryInfoRenderer]!=]];videoPrimaryInfoRenderer;viewCount;videoViewCountRenderer;viewCount;simpleText]; ;0];,;;.;]"]
    $!jsonSet[reshttptest;author;$env[reshttp2;contents;twoColumnWatchNextResults;results;results;contents;$arrayFindIndex[resfindindex;g;$checkCondition[$env[g;videoSecondaryInfoRenderer]!=]];videoSecondaryInfoRenderer;owner;videoOwnerRenderer;title;runs;0;text]]
    $!jsonSet[reshttptest;isPrivate;$checkCondition[$arrayFindIndex[resfindindex;g;$checkCondition[$env[g;videoPrimaryInfoRenderer]!=]]==-1]]
    $!jsonSet[reshttptest;isLiveContent;$if[$env[reshttp2;contents;twoColumnWatchNextResults;results;results;contents;$arrayFindIndex[resfindindex;g;$checkCondition[$env[g;videoPrimaryInfoRenderer]!=]];videoPrimaryInfoRenderer;viewCount;videoViewCountRenderer;isLive]!=;$env[reshttp2;contents;twoColumnWatchNextResults;results;results;contents;$arrayFindIndex[resfindindex;g;$checkCondition[$env[g;videoPrimaryInfoRenderer]!=]];videoPrimaryInfoRenderer;viewCount;videoViewCountRenderer;isLive];$startsWith[$env[reshttp2;contents;twoColumnWatchNextResults;results;results;contents;$arrayFindIndex[resfindindex;g;$checkCondition[$env[g;videoPrimaryInfoRenderer]!=]];videoPrimaryInfoRenderer;dateText;simpleText];Started streaming]]]
    $let[results;{"status":null,"results":$if[$env[reshttptest;videoId]==;null;$jsonStringify[reshttptest]]}]
    ;
    $if[$env[reshttp;responseContext;visitorData]!=;$setCache[initclientmusic;authmusic_youtube_visitor;$env[reshttp;responseContext;visitorData]]]
    $let[results;{"status":null,"results":$if[$env[reshttp;videoDetails]==;null;$env[reshttp;videoDetails]]}]
    ]
    ;retry]
    $callLocalFunction[refreshyt;false]
    ]
    $if[$env[filterid;type]==soundcloud;
    $let[keturl;https://$get[spliturl]]
    $if[$charCount[$advancedTextSplit[$get[spliturl];/;0];.]>=2;$!djsEval[fetch(ctx.getKeyword("keturl"), { method: "HEAD" }).then(a => ctx.setKeyword("keturl", a.url)).catch()]]
    $let[tryattempt;0]
    $localFunction[refreshsoundcloud;
    $if[$env[retry]==true;$letSum[tryattempt;1]]
    $onlyIf[$get[tryattempt]<3;$return]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpAddHeader[Accept-Encoding;gzip, br]
    $httpSetContentType[Text]
    $let[httpscf;$httpRequest[https://api-v2.soundcloud.com/resolve?url=$get[keturl]&client_id=$getCache[initclientmusic;authmusic_soundcloud];GET;reshttp]]
    $if[$get[httpscf]==429;$callLocalFunction[refreshsoundcloud;true] $return]
    $let[a;$env[reshttp]]
    $return
    ;retry]
    $callLocalFunction[refreshsoundcloud;false]
    $let[results;{"status":null,"results":$if[$get[a]=={};null;$get[a]]}]
    ]
    $if[$env[filterid;type]==spotify;
    $let[tryattempt;0]
    $localFunction[refreshspotify;
    $if[$env[retry]==true;
    $onlyIf[$get[tryattempt]<3;$return]
    $callFunction[generateAuth;spotify;;false]
    $letSum[tryattempt;1]
    ]
    $let[mdhedroute_spotify;{
    "App-Platform": "WebPlayer",
    "Authorization": "Bearer $getCache[initclientmusic;authmusic_spotify]",
    "Sec-Fetch-Site": "none",
    "User-Agent": "$get[agent]"
    }]
    $let[mdquery;https://api.spotify.com/v1/tracks/$advancedTextSplit[$env[filterid;id];/;1]?market=US]
    $let[b;$djsEval[const { request, Agent } = require("undici")\\; request(ctx.getKeyword("mdquery"), { dispatcher: new Agent({ connect: { family: 4 } }), headers: JSON.parse(ctx.getKeyword("mdhedroute_spotify")), method: "GET" }).then(a => { ctx.setKeyword('http', a.statusCode)\\; return a.body.text() }).catch()]]
    $onlyIf[$or[$get[http]==401;$get[http]==400]!=true;$callLocalFunction[refreshspotify;true]]
    $if[$or[$get[http]==403;$get[http]==429];
    $httpAddHeader[Accept-Encoding;gzip, br]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpSetContentType[Text]
    $let[http;$httpRequest[https://open.spotify.com/embed/$env[filterid;id]?utm_source=oembed;GET;a]]
    $if[$get[http]==403;
    $let[a;null]
    ;
    $let[a;$advancedTextSplit[$env[a];type="application/json">;1;</script>;0]]
    ]
    ;
    $let[a;$get[b]]
    ]
    $let[results;{"status":null,"results":$if[$get[a]==;null;$get[a]]}]
    ;retry]
    $callLocalFunction[refreshspotify;false]
    ]
    $if[$env[filterid;type]==applemusic;
    $httpAddHeader[Accept-Encoding;gzip, br]
    $httpAddHeader[Accept-Language;en]
    $httpAddHeader[Accept;*/*]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpSetContentType[Text]
    $let[http;$httpRequest[https://itunes.apple.com/lookup?id=$env[filterid;id];GET;a]]
    $jsonLoad[a;$env[a]]
    $let[results;{"status":null,"results":$if[$env[a;results;0]==;null;$env[a;results;0]]}]
    ]
    $if[$env[filterid;type]==tiktokmob;
    $let[testtempjr;$djsEval[fetch("https://vt.tiktok.com/$env[filterid;id]", { method: "HEAD" }).then(a => a.url).catch()]]
    $jsonLoad[filterid;$callFunction[filterMediaID;$get[testtempjr]]]
    $onlyIf[$or[$env[filterid;id]==;$env[filterid;id]==null]!=true;$return]
    ]
    $if[$env[filterid;type]==tiktok;
    $let[ttcounting;0]
    $localFunction[fetchttdl;
    $if[$get[ttcounting]>=10;$return]
    $if[$env[retry]==true;$letSum[ttcounting;1]]
    $httpAddHeader[Accept-Encoding;gzip, br]
    $httpAddHeader[Accept-Language;en]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpAddHeader[Cookie;$getCache[initclientmusic;authmusic_tiktok]]
    $httpAddHeader[Referer;https://www.tiktok.com/404]
    $httpAddHeader[Sec-Fetch-Dest;empty]
    $httpAddHeader[Sec-Fetch-Site;same-origin]
    $httpSetContentType[Text]
    $let[http;$httpRequest[https://www.tiktok.com/share/video/$env[filterid;id]?_r=1;GET]]
    $jsonLoad[a;$advancedTextSplit[$httpResult;"webapp.video-detail":;1;,"webapp;0]]
    $if[$isJSON[$env[a]]==false;$callLocalFunction[fetchttdl;true] $return]
    ;retry]
    $callLocalFunction[fetchttdl;false]
    $if[$env[a;statusCode]!=0;$return[{"status":null,"results":{"error":"$env[a;statusMsg]"}}]]
    $jsonLoad[b;$default[$env[a;itemInfo;itemStruct];{}]]
    $if[$env[b;author]==;
    $httpAddHeader[Accept-Encoding;gzip, br]
    $httpAddHeader[Accept-Language;en]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpAddHeader[Cookie;$getCache[initclientmusic;authmusic_tiktok]]
    $httpSetContentType[Text]
    $let[http;$httpRequest[https://www.tiktok.com/embed/v2/$env[filterid;id];GET]]
    $if[$or[$get[http]==200;$isJSON[$httpResult]]==false;$return[{"status":null,"results":{"error":"IP blocked"}}]]
    $jsonLoad[a;$advancedTextSplit[$httpResult;type="application/json">;1;</script>;0]]
    $onlyIf[$env[a;source;data;/embed/v2/$env[filterid;id];videoData]!=;$return[{"status":null,"results":{"error":"Content unavailable"}}]]
    $jsonLoad[b;$env[a;source;data;/embed/v2/$env[filterid;id];videoData]]
    ]
    $let[results;{"status":null,"results":$if[$env[b]==;null;$jsonStringify[b]]}]
    ]
    $if[$env[filterid;type]==tiktokmusic;
    $let[tryattempt;0]
    $localFunction[refreshvm;
    $if[$env[retry]==true;
    $onlyIf[$get[tryattempt]<10;$return]
    $letSum[tryattempt;1]
    ]
    $httpSetContentType[Text]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpAddHeader[Accept;application/json]
    $httpAddHeader[Accept-Encoding;gzip, br]
    $httpAddHeader[Accept-Language;en]
    $httpAddHeader[Cookie;$getCache[initclientmusic;authmusic_tiktok]]
    $httpAddHeader[X-Khronos;$round[$divide[$getTimestamp;1000]]]
    $httpAddHeader[X-Argus;]
    $c[Doesn't require to solve challenge for this, for now]
    $!httpRequest[https://api-boot.tiktokv.com/aweme/v1/music/aweme/?music_id=$env[filterid;id]&aid=1233&device_id=$getCache[initclientmusic;authmusic_tiktok_did]&odinId=$getCache[initclientmusic;authmusic_tiktok_odinid]&user_is_login=true&cookie_enabled=true&region=&referer=;GET;a]
    $onlyIf[$env[a]!=;$callLocalFunction[refreshvm;true]]
    $jsonLoad[a;$env[a]]
    $jsonLoad[a;$env[a;aweme_list]]
    $let[index;$arrayFindIndex[a;b;$checkCondition[$env[b;added_sound_music_info;mid]==$env[filterid;id]]]]
    $if[$get[index]==-1;
    $httpAddHeader[Accept-Encoding;gzip, br]
    $httpAddHeader[Accept-Language;en]
    $httpAddHeader[Accept;*/*]
    $httpAddHeader[User-Agent;$callFunction[configMusic;default_userAgent_bot]]
    $httpSetContentType[Text]
    $let[nsdgltt;$httpRequest[https://www.tiktok.com/oembed?url=https://www.tiktok.com/music/-$env[filterid;id];GET;nnoian]]
    $if[$get[nsdgltt]!=200;$return]
    $jsonLoad[nsdglvjon;$env[nnoian]]
    $let[stctitle;$env[nsdglvjon;author_name]]
    $httpAddHeader[Accept-Encoding;gzip, br]
    $httpAddHeader[Accept-Language;en]
    $httpAddHeader[Accept;*/*]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpAddHeader[Cookie;$getCache[initclientmusic;authmusic_tiktok]]
    $httpAddHeader[X-Khronos;$round[$divide[$getTimestamp;1000]]]
    $httpAddHeader[X-Argus;]
    $!httpRequest[https://api-boot.tiktokv.com/aweme/v1/music/search/?count=10&cursor=0&aid=1988&device_id=$getCache[initclientmusic;authmusic_tiktok_did]&odinId=$getCache[initclientmusic;authmusic_tiktok_odinid]&user_is_login=false&cookie_enabled=true&region=&referer=&keyword=$get[stctitle];GET;c]
    $onlyIf[$env[c]!=;$return]
    $jsonLoad[c;$env[c]]
    $jsonLoad[c;$env[c;music_info_list]]
    $jsonLoad[c;$env[c;$arrayFindIndex[c;k;$checkCondition[$env[k;music;id_str]==$env[filterid;id]]]]]
    $let[results;{"status":null,"results":$if[$env[c]==;null;$env[c;music]]}]
    ;
    $let[results;{"status":null,"results":$if[$env[a;$get[index]]==;null;$env[a;$get[index];music]]}]
    ]
    ;retry]
    $callLocalFunction[refreshvm;false]
    ]
    $if[$env[filterid;type]==facebook;
    $let[url;https://web.facebook.com$advancedTextSplit[$get[url];facebook.com;1]]
    $!djsEval[fetch(ctx.getKeyword("url"), { method: "HEAD", headers: { "Accept": "text/html, */*" } }).then(a => ctx.setKeyword("url", a.url)).catch()]
    $jsonLoad[resolvedfbid;$callFunction[filterMediaID;$get[url]]]
    $httpSetBody[lsd=$getCache[initclientmusic;authmusic_instagram_lsd]&fb_api_caller_class=RelayModern&fb_api_req_friendly_name=PolarisLoggedOutDesktopWWWPostRootContentQuery&server_timestamps=true&variables={"feedLocation":"COMET_MEDIA_VIEWER","privacySelectorRenderLocation":"COMET_MEDIA_VIEWER","renderLocation":"comet_media_viewer","nodeID":"$default[$env[resolvedfbid;id];$env[filterid;id]]","scale":1,"shouldShowComments":false}&doc_id=28067965802883859]
    $httpAddHeader[Accept;*/*]
    $httpAddHeader[Content-Type;application/x-www-form-urlencoded]
    $httpAddHeader[Accept-Encoding;gzip, br]
    $httpAddHeader[Sec-Fetch-Site;same-origin]
    $httpAddHeader[X-ASBD-ID;359341]
    $httpAddHeader[X-FB-LSD;$getCache[initclientmusic;authmusic_instagram_lsd]]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpSetContentType[Text]
    $let[uynsdfp;$httpRequest[https://www.facebook.com/api/graphql;POST;noiio]]
    $arrayLoad[kka;
;$env[noiio]]
    $let[results;{"status":null,"results":$if[$typeof[$env[kka;0]]==object;$env[kka;0];null]}]
    ]
    $if[$env[filterid;type]==instagram;
    $c[Instagram GraphQL Api]
    $httpSetBody[lsd=$getCache[initclientmusic;authmusic_instagram_lsd]&fb_api_caller_class=RelayModern&fb_api_req_friendly_name=PolarisLoggedOutDesktopWWWPostRootContentQuery&server_timestamps=true&variables={"media_id":"$callFunction[codeToIdInstagram;$advancedTextSplit[$env[filterid;id];/;$charCount[$env[filterid;id];/]]]"}&doc_id=27130156389949648]
    $httpAddHeader[Accept;*/*]
    $httpAddHeader[Content-Type;application/x-www-form-urlencoded]
    $httpAddHeader[Accept-Encoding;gzip, br]
    $httpAddHeader[Sec-Fetch-Site;same-origin]
    $if[$getCache[initclientmusic;authmusic_instagram_csrf]!=;
    $httpAddHeader[X-CSRFToken;$getCache[initclientmusic;authmusic_instagram_csrf]]
    ]
    $httpAddHeader[X-ASBD-ID;359341]
    $httpAddHeader[X-FB-LSD;$getCache[initclientmusic;authmusic_instagram_lsd]]
    $httpAddHeader[X-IG-App-ID;$default[$getCache[initclientmusic;authmusic_instagram_appid];936619743392459]]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpSetContentType[Text]
    $let[uynsdfp;$httpRequest[https://www.instagram.com/api/graphql;POST]]
    $if[$typeof[$httpResult]==object;$jsonLoad[lck;$httpResult]]
    $if[$or[$env[lck]==;$env[lck;data;require_login]==true;$get[uynsdfp]==403;$get[uynsdfp]==429];
    $c[Instagram Embed Webpage]
    $httpAddHeader[Accept;text/html, */*]
    $httpAddHeader[Accept-Language;en]
    $httpAddHeader[Sec-Fetch-Dest;iframe]
    $httpAddHeader[Sec-Fetch-Site;none]
    $httpAddHeader[Accept-Encoding;gzip, br]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpAddHeader[Referer;https://www.instagram.com/]
    $httpSetContentType[Text]
    $let[uynsdf;$httpRequest[https://www.instagram.com/p/$advancedTextSplit[$env[filterid;id];/;$charCount[$env[filterid;id];/]]/embed?_fb_noscript=1;GET]]
    $if[$or[$get[uynsdf]==403;$get[uynsdf]==429];
    $c[Instagram Webpage]
    $httpAddHeader[Accept;text/html, */*]
    $httpAddHeader[Accept-Language;en]
    $httpAddHeader[Accept-Encoding;gzip, br]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpAddHeader[Sec-Fetch-Dest;document]
    $httpAddHeader[Sec-Fetch-Site;none]
    $httpSetContentType[Text]
    $let[uynsd;$httpRequest[https://www.instagram.com/p/$advancedTextSplit[$env[filterid;id];/;$charCount[$env[filterid;id];/]];GET]]
    $onlyIf[$or[$get[uynsd]==403;$get[uynsd]==429]!=true;$return[{"status":null,"results":{"error":"Sign in for view this content"}}]]
    $arrayLoad[iru;script type="application/json";$httpResult]
    $jsonLoad[irk;$default[$advancedTextSplit[$env[iru;$arrayFindIndex[iru;r;$checkCondition[$advancedTextSplit[$env[r];"RelayPrefetchedStreamCache";1;"xig_polaris_media";1]!=]]];data-sjs>;1;</script>;0];{}]]
    $jsonLoad[lcpr;$default[$env[irk;require;0;3;0;__bbox;require];{}]]
    $let[findbboxindex;$arrayFindIndex[lcpr;ot;$checkCondition[$env[ot;3;1;__bbox;result;data;xig_polaris_media]!=]]]
    $jsonLoad[lck;$default[$env[irk;require;0;3;0;__bbox;require;$get[findbboxindex];3;1;__bbox;result;data;xig_polaris_media;if_not_gated_logged_out];{}]]
    $onlyIf[$env[lck;pk]!=;$return[{"status":null,"results":{"error":"Not a video or you don't have permission to view it"}}]]
    ;
    $let[temdata;$advancedTextSplit[$httpResult;"contextJSON":";1;"}\\]\\];0]]
    $jsonLoad[kvo;$replace[$get[temdata];\\\\\;]]
    $jsonLoad[lck;$env[kvo;gql_data]]
    ]
    ;
    $jsonLoad[lck;$default[$env[lck;data;xig_polaris_media;if_not_gated_logged_out];{}]]
    ]
    $let[results;{"status":null,"results":$jsonStringify[lck]}]
    ]
    $if[$env[filterid;type]==instagramaudio;
    $httpSetBody[audio_cluster_id=$env[filterid;id]&max_id&original_sound_audio_asset_id=$env[filterid;id]]
    $httpAddHeader[Content-Type;application/x-www-form-urlencoded]
    $httpAddHeader[User-Agent;Instagram 414.0.0 Android]
    $httpAddHeader[Sec-Fetch-Site;same-origin]
    $httpAddHeader[Origin;https://i.instagram.com]
    $httpAddHeader[Accept-Language;en]
    $httpAddHeader[Accept-Encoding;gzip, br]
    $httpSetContentType[Text]
    $!httpRequest[https://i.instagram.com/api/v1/clips/music/;POST]
    $onlyIf[$isJSON[$httpResult];$return]
    $jsonLoad[lkig;$httpResult]
    $let[results;{"status":null,"results":$if[$env[lkig;items;0]==;null;$jsonStringify[lkig]]}]
    ]
    $if[$env[filterid;type]==bandcamp;
    $httpSetContentType[Text]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpAddHeader[Accept-Encoding;gzip, br]
    $httpAddHeader[Accept-Language;en]
    $!httpRequest[$env[filterid;id];GET]
    $let[a;$advancedTextSplit[$httpResult;data-tralbum=";1;";0]]
    $let[a;$djsEval[require("entities").decodeHTML(ctx.getKeyword("a"))]]
    $jsonLoad[a;$default[$get[a];{}]]
    $if[$env[a;trackinfo;0;artist]==null;
    $let[b;$advancedTextSplit[$httpResult;data-band=";1;";0]]
    $let[b;$djsEval[require("entities").decodeHTML(ctx.getKeyword("b"))]]
    $jsonLoad[b;$default[$get[b];{}]]
    $!jsonSet[a;trackinfo;0;artist;$env[b;name]]
    ]
    $let[results;{"status":null,"results":$if[$env[a;trackinfo]==;null;$env[a;trackinfo;0]]}]
    ]
    $if[$env[filterid;type]==twitter;
    $httpAddHeader[Accept-Encoding;gzip, br]
    $httpAddHeader[Accept-Language;en]
    $httpAddHeader[Accept;*/*]
    $httpAddHeader[Sec-Fetch-Dest;iframe]
    $httpAddHeader[Sec-Fetch-Site;none]
    $httpAddHeader[User-Agent;$get[agent]]
    $!httpRequest[https://cdn.syndication.twimg.com/tweet-result?id=$env[filterid;id]&lang=en&token=abc;GET]
    $if[$typeof[$httpResult]==string;$return[{"status":null,"results":{"error":"Item not found"}}]]
    $jsonLoad[thers;$httpResult]
    $if[$env[thers;tombstone;text;text]!=;$return[{"status":null,"results":{"error":"$env[thers;tombstone;text;text]"}}]]
    $let[results;{"status":null,"results":$if[$env[thers]==;null;$jsonStringify[thers]]}]
    ]
    $if[$env[filterid;type]==threads;
    $if[$advancedTextSplit[$get[url];/share/;1]!=;
    $let[sharelk;$get[url]]
    $let[resolvedlk;$djsEval[fetch(ctx.getKeyword("sharelk")).then(a=>a.url).catch()]]
    $jsonLoad[filterid;$callFunction[filterMediaID;$get[resolvedlk]]]
    ]
    $httpAddHeader[Accept;text/html, */*]
    $httpAddHeader[Accept-Language;en]
    $httpAddHeader[Accept-Encoding;gzip, br]
    $httpAddHeader[User-Agent;$get[agent]]
    $httpAddHeader[Sec-Fetch-Dest;iframe]
    $httpAddHeader[Sec-Fetch-Site;none]
    $httpAddHeader[Referer;https://www.threads.com/]
    $httpSetContentType[Text]
    $let[uynsd;$httpRequest[https://www.threads.com/@/post/$env[filterid;id]/embed?_fb_noscript=1;GET]]
    $onlyIf[$or[$get[uynsd]==403;$get[uynsd]==429]!=true;$return[{"status":null,"results":{"error":"Sign in for view this content"}}]]
    $let[vra1;$default[$advancedTextSplit[$httpResult;class="HeaderLink"><span>;1;</span>;0];null]]
    $let[vra2;$default[$advancedTextSplit[$httpResult;class="BodyTextContainer"><span>;1;</span>;0];null]]
    $let[vra3;$default[$advancedTextSplit[$httpResult;source src=";1;";0];]]
    $let[vra1;$djsEval[require("entities").decodeHTML(ctx.getKeyword("vra1"))]]
    $let[vra2;$djsEval[require("entities").decodeHTML(ctx.getKeyword("vra2"))]]
    $let[vra3;$djsEval[require("entities").decodeHTML(ctx.getKeyword("vra3"))]]
    $jsonLoad[rty;{}]
    $!jsonSet[rty;author;$get[vra1]]
    $!jsonSet[rty;title;$get[vra2]]
    $!jsonSet[rty;media;$get[vra3]]
    $!jsonSet[rty;postid;$env[filterid;id]]
    $arrayLoad[thimgs]
    $arrayLoad[thraw;MediaScrollImageContainer"><img class="img" src=";$httpResult]
    $arraySlice[thraw;thraw;1;10]
    $arrayForEach[thraw;thim;$arrayPush[thimgs;$djsEval[require("entities").decodeHTML(ctx.getEnvironmentKey("thim").split('"')[0\\])]]]
    $arrayPush[thimgs;$advancedTextSplit[$httpResult;og:image" content=";1;";0]]
    $!jsonSet[rty;images;$env[thimgs]]
    $let[results;{"status":null,"results":$jsonStringify[rty]}]
    ]

    $let[resultforeturn;$get[results]]
    $return[$if[$and[$env[limitChar]==true;$env[limitChar]!=false];$cropText[$get[resultforeturn];0;2000;];$get[resultforeturn]]]
    `
} satisfies IForgeFunction;
